-- CORE SQL QUERIES

-- Display all sales records ordered from the highest sale amount to the lowest sale amount.
SELECT *
FROM sales
ORDER BY sales DESC;

-- Display all shipped orders.
SELECT *
FROM sales
WHERE status = 'Shipped';

-- Calculate the total sales generated from all orders.
SELECT 
	SUM(sales) AS total_sales
FROM sales;

-- Calculate the average sales value per order.
SELECT 
	ROUND(AVG(sales), 2) AS avg_sales
FROM sales;

-- Count the total number of orders in the dataset.
SELECT 
	COUNT(*) AS total_orders
FROM sales

---- Count the number of orders in each order status.
SELECT 
	status,
	COUNT(*) AS number_of_orders
FROM sales
GROUP BY status
ORDER BY number_of_orders DESC;

-- Calculate total revenue generated by each product line.
SELECT 
	productline,
	SUM(sales) AS total_revenue
FROM sales
GROUP BY productline
ORDER BY total_revenue DESC;

-- Display countries that generated more than $100,000 in sales.
SELECT 
	country,
	SUM(sales) AS total_sales
FROM sales
GROUP BY country
HAVING 	SUM(sales) > 100000 
ORDER BY total_sales DESC;


-- ADVANCED SQL CONCEPTS
-- Display customers whose total spending is greater than the average customer spending.
SELECT 
	customername,
	SUM(sales) AS total_sales
FROM sales
GROUP BY customername
HAVING SUM(sales) >
(
SELECT 
	AVG(customer_sales)
FROM(
	SELECT 
		customername,
		SUM(sales) AS customer_sales
	FROM sales
	GROUP BY customername
	)avg_sales
)ORDER BY total_sales DESC;

-- Identify product lines whose revenue is higher than the average revenue generated by all product lines.
SELECT 
	productline,
	SUM(sales) AS total_revenue
FROM sales
GROUP BY productline
HAVING SUM(sales) >
(
SELECT 
	AVG(product_revenue)
FROM
(
SELECT 
		productline,
		SUM(sales) AS product_revenue
		FROM sales
	GROUP BY productline
	) AS product_summary
)ORDER BY total_revenue DESC;

-- WINDOW FUNCTION 
-- Assign a unique sequential number to each customer's orders based on the order date.
SELECT
    customername,
    ordernumber,
    orderdate,
    ROW_NUMBER() OVER(
        ORDER BY orderdate
    ) AS row_num
FROM sales;

-- Rank customers according to the total sales they generated.
SELECT
    customername,
    SUM(sales) AS total_sales,
    RANK() OVER(
        ORDER BY SUM(sales) DESC
    ) AS customer_rank
FROM sales
GROUP BY customername
ORDER BY customer_rank;

-- Rank customers within each country based
-- on the total sales they generated.
SELECT
    country,
    customername,
    SUM(sales) AS total_sales,
    RANK() OVER(
        PARTITION BY country
        ORDER BY SUM(sales) DESC
    ) AS country_rank
FROM sales
GROUP BY
    country,
    customername
ORDER BY
    country,
    country_rank;